### ISSUE TITLE
FileNotFoundException

### ISSUE THREAD

**Issue by tester4252** [openasn1/openASN.1#1]
Caused by: java.io.FileNotFoundException: config\GlobalConfig.xml  
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.github.openasn1.compiler.utils.GlobalConfiguration.<init>(GlobalConfiguration.java:48)

**Comment by onderson** [comment]
it is in jar file already. could you please describe how you use it?
